language: objective-c
osx_image: xcode8.1
xcode_workspace: sync-ios-app.xcworkspace
xcode_scheme: sync-ios-app
xcode_sdk: iphonesimulator

notifications:
  irc: "irc.freenode.org#feedhenry"

script:
  - xcodebuild clean build -workspace sync-ios-app.xcworkspace -scheme sync-ios-app -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6' GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES

branches:
  only:
    - master
    - xcode8